---
- name: Project Flow Fusion - VM Deployment
  hosts: localhost

  vars:
    project_code_name: flow-fusion

  tasks:
    - name: Create folder
      vmware.vmware.folder:
        hostname: '{{ lookup("env", "VMWARE_HOST" }}'
        username: '{{ lookup("env", "VMWARE_USER" }}'
        password: '{{ lookup("env", "VMWARE_PASSWORD" }}'
        validate_certs: False
        absolute_path: "lab/vm/tm/workshops/automation-across-silos/{{ project_code_name }}"
        state: present
